// Ticker universe for /markets — S&P 500 + SOXX + DRAM memory names.
//
// Two tiers:
//   HOT_TICKERS   — ~50 most-liquid options names; the dxlink-worker
//                   subscribes to these in real-time. UI shows a green
//                   "LIVE" dot next to them.
//   SP500_TICKERS — full S&P 500 plus SOXX/memory additions. The
//                   long-tail names aren't streamed; the UI lets users
//                   pick them anyway and falls back to Yahoo (15-min
//                   delayed) for compute-gex.
//
// Keep the worker's `dxlink-worker/src/tickers.ts` TRACKED_TICKERS
// synced to HOT_TICKERS by hand — the worker is a Deno process and
// can't `import` from this module.
//
// Labels are deliberately terse ("Apple" not "Apple Inc.") to fit on
// mobile rows in the drawer.

export const HOT_TICKERS = [
  // Index ETFs (highest options volume on the planet)
  { symbol: 'SPY',   label: 'S&P 500' },
  { symbol: 'QQQ',   label: 'Nasdaq-100' },
  { symbol: 'IWM',   label: 'Russell 2000' },
  { symbol: 'DIA',   label: 'Dow Jones' },
  // Volatility / commodity / rates ETFs (vol-trader staples)
  { symbol: 'GLD',   label: 'Gold' },
  { symbol: 'SLV',   label: 'Silver' },
  { symbol: 'TLT',   label: '20y Treasury' },
  { symbol: 'USO',   label: 'Crude Oil' },
  // Mega-cap tech
  { symbol: 'AAPL',  label: 'Apple' },
  { symbol: 'MSFT',  label: 'Microsoft' },
  { symbol: 'NVDA',  label: 'Nvidia' },
  { symbol: 'GOOGL', label: 'Alphabet A' },
  { symbol: 'AMZN',  label: 'Amazon' },
  { symbol: 'META',  label: 'Meta' },
  { symbol: 'TSLA',  label: 'Tesla' },
  // Big tech / SaaS
  { symbol: 'AMD',   label: 'AMD' },
  { symbol: 'AVGO',  label: 'Broadcom' },
  { symbol: 'INTC',  label: 'Intel' },
  { symbol: 'ORCL',  label: 'Oracle' },
  { symbol: 'CRM',   label: 'Salesforce' },
  { symbol: 'ADBE',  label: 'Adobe' },
  { symbol: 'NFLX',  label: 'Netflix' },
  { symbol: 'NOW',   label: 'ServiceNow' },
  // Semis (foundry / equipment / mobile-silicon / networking-silicon)
  { symbol: 'TSM',   label: 'Taiwan Semi' },
  { symbol: 'ASML',  label: 'ASML' },
  { symbol: 'AMAT',  label: 'Applied Materials' },
  { symbol: 'LRCX',  label: 'Lam Research' },
  { symbol: 'QCOM',  label: 'Qualcomm' },
  { symbol: 'MRVL',  label: 'Marvell' },
  // Memory / DRAM / NAND
  { symbol: 'MU',    label: 'Micron' },
  { symbol: 'WDC',   label: 'Western Digital' },
  { symbol: 'SNDK',  label: 'SanDisk' },
  // AI infrastructure (data center, GPU cloud, networking, servers)
  { symbol: 'VRT',   label: 'Vertiv' },
  { symbol: 'DLR',   label: 'Digital Realty' },
  { symbol: 'EQIX',  label: 'Equinix' },
  { symbol: 'CRWV',  label: 'CoreWeave' },
  { symbol: 'NBIS',  label: 'Nebius' },
  { symbol: 'IREN',  label: 'Iris Energy' },
  { symbol: 'BTMR',  label: 'Bitmine Immersion' },
  { symbol: 'SMCI',  label: 'Super Micro' },
  { symbol: 'ANET',  label: 'Arista' },
  { symbol: 'NOK',   label: 'Nokia' },
  // Banks
  { symbol: 'JPM',   label: 'JPMorgan' },
  { symbol: 'GS',    label: 'Goldman Sachs' },
  { symbol: 'BAC',   label: 'Bank of America' },
  { symbol: 'WFC',   label: 'Wells Fargo' },
  // Healthcare / pharma
  { symbol: 'LLY',   label: 'Eli Lilly' },
  { symbol: 'NVO',   label: 'Novo Nordisk' },
  { symbol: 'PFE',   label: 'Pfizer' },
  { symbol: 'MRK',   label: 'Merck' },
  { symbol: 'JNJ',   label: 'Johnson & Johnson' },
  { symbol: 'UNH',   label: 'UnitedHealth' },
  { symbol: 'ABBV',  label: 'AbbVie' },
  // Consumer
  { symbol: 'WMT',   label: 'Walmart' },
  { symbol: 'COST',  label: 'Costco' },
  { symbol: 'HD',    label: 'Home Depot' },
  { symbol: 'MCD',   label: "McDonald's" },
  { symbol: 'NKE',   label: 'Nike' },
  { symbol: 'DIS',   label: 'Disney' },
  // Energy (oil majors)
  { symbol: 'XOM',   label: 'ExxonMobil' },
  { symbol: 'CVX',   label: 'Chevron' },
  { symbol: 'COP',   label: 'ConocoPhillips' },
  // AI power / nuclear renaissance — power demand is the AI buildout's
  // chokepoint, these names move on data-center contract announcements.
  { symbol: 'VST',   label: 'Vistra' },
  { symbol: 'CEG',   label: 'Constellation' },
  { symbol: 'NEE',   label: 'NextEra Energy' },
  { symbol: 'SMR',   label: 'NuScale' },
  { symbol: 'OKLO',  label: 'Oklo' },
  { symbol: 'CCJ',   label: 'Cameco' },
  { symbol: 'BE',    label: 'Bloom Energy' },
  // Rare earths / lithium — supply-chain plays (US strategic materials)
  { symbol: 'MP',    label: 'MP Materials' },
  { symbol: 'LAC',   label: 'Lithium Americas' },
  { symbol: 'USAR',  label: 'USA Rare Earth' },
  { symbol: 'CRML',  label: 'Critical Metals' },
  { symbol: 'UUU',   label: 'Universal Stainless' },
  // Liquid retail / meme / fintech
  { symbol: 'COIN',  label: 'Coinbase' },
  { symbol: 'PLTR',  label: 'Palantir' },
  { symbol: 'UBER',  label: 'Uber' },
  { symbol: 'ARM',   label: 'Arm' },
  { symbol: 'BABA',  label: 'Alibaba' },
  { symbol: 'GME',   label: 'GameStop' },
  // ── Leopold Aschenbrenner portfolio (AI buildout: data-center
  //    operators, GPU cloud, power/oilfield infra, memory). INTC,
  //    SNDK, CRWV, BE already covered in groups above.
  { symbol: 'PUMP',  label: 'ProPetro' },
  { symbol: 'KEEL',  label: 'Keel Infrastructure' },
  { symbol: 'RIOT',  label: 'Riot Platforms' },
  { symbol: 'SEI',   label: 'Solaris Energy Infra' },
  { symbol: 'HUT',   label: 'Hut 8' },
  { symbol: 'LBRT',  label: 'Liberty Energy' },
  { symbol: 'EQT',   label: 'EQT Corp' },
  { symbol: 'KRC',   label: 'Kilroy Realty' },
  { symbol: 'CLSK',  label: 'CleanSpark' },
  { symbol: 'BW',    label: 'Babcock & Wilcox' },
  { symbol: 'TSEM',  label: 'Tower Semiconductor' },
  { symbol: 'PSIX',  label: 'Power Solutions Intl' },
  { symbol: 'COHR',  label: 'Coherent' },
  { symbol: 'CIFR',  label: 'Cipher Mining' },
  { symbol: 'CORZ',  label: 'Core Scientific' },
  { symbol: 'LITE',  label: 'Lumentum' },
  { symbol: 'WYFI',  label: 'WhiteFiber' },
  { symbol: 'APLD',  label: 'Applied Digital' },
]

// Full S&P 500 constituents (Nov 2025), plus a handful of additional
// SOXX semis (TSM, ASML — ADRs not in S&P 500) and DRAM/memory names
// not already covered. Labels are intentionally compact.
//
// This list is also the universe shown in the picker drawer; the user
// can search by symbol or company name to find any of them.
export const SP500_TICKERS = [
  // A
  { symbol: 'A', label: 'Agilent' },
  { symbol: 'AAPL', label: 'Apple' },
  { symbol: 'ABBV', label: 'AbbVie' },
  { symbol: 'ABNB', label: 'Airbnb' },
  { symbol: 'ABT', label: 'Abbott Labs' },
  { symbol: 'ACGL', label: 'Arch Capital' },
  { symbol: 'ACN', label: 'Accenture' },
  { symbol: 'ADBE', label: 'Adobe' },
  { symbol: 'ADI', label: 'Analog Devices' },
  { symbol: 'ADM', label: 'Archer Daniels' },
  { symbol: 'ADP', label: 'ADP' },
  { symbol: 'ADSK', label: 'Autodesk' },
  { symbol: 'AEE', label: 'Ameren' },
  { symbol: 'AEP', label: 'American Electric Power' },
  { symbol: 'AES', label: 'AES Corp' },
  { symbol: 'AFL', label: 'Aflac' },
  { symbol: 'AIG', label: 'AIG' },
  { symbol: 'AIZ', label: 'Assurant' },
  { symbol: 'AJG', label: 'Arthur J. Gallagher' },
  { symbol: 'AKAM', label: 'Akamai' },
  { symbol: 'ALB', label: 'Albemarle' },
  { symbol: 'ALGN', label: 'Align Technology' },
  { symbol: 'ALL', label: 'Allstate' },
  { symbol: 'ALLE', label: 'Allegion' },
  { symbol: 'AMAT', label: 'Applied Materials' },
  { symbol: 'AMCR', label: 'Amcor' },
  { symbol: 'AMD', label: 'AMD' },
  { symbol: 'AME', label: 'Ametek' },
  { symbol: 'AMGN', label: 'Amgen' },
  { symbol: 'AMP', label: 'Ameriprise' },
  { symbol: 'AMT', label: 'American Tower' },
  { symbol: 'AMZN', label: 'Amazon' },
  { symbol: 'ANET', label: 'Arista Networks' },
  { symbol: 'ANSS', label: 'Ansys' },
  { symbol: 'AON', label: 'Aon' },
  { symbol: 'AOS', label: 'A.O. Smith' },
  { symbol: 'APA', label: 'APA Corp' },
  { symbol: 'APD', label: 'Air Products' },
  { symbol: 'APH', label: 'Amphenol' },
  { symbol: 'APO', label: 'Apollo Global' },
  { symbol: 'APTV', label: 'Aptiv' },
  { symbol: 'ARE', label: 'Alexandria Real Estate' },
  { symbol: 'ATO', label: 'Atmos Energy' },
  { symbol: 'AVB', label: 'AvalonBay' },
  { symbol: 'AVGO', label: 'Broadcom' },
  { symbol: 'AVY', label: 'Avery Dennison' },
  { symbol: 'AWK', label: 'American Water Works' },
  { symbol: 'AXON', label: 'Axon Enterprise' },
  { symbol: 'AXP', label: 'American Express' },
  { symbol: 'AZO', label: 'AutoZone' },
  // B
  { symbol: 'BA', label: 'Boeing' },
  { symbol: 'BAC', label: 'Bank of America' },
  { symbol: 'BALL', label: 'Ball Corp' },
  { symbol: 'BAX', label: 'Baxter' },
  { symbol: 'BBY', label: 'Best Buy' },
  { symbol: 'BDX', label: 'Becton Dickinson' },
  { symbol: 'BEN', label: 'Franklin Resources' },
  { symbol: 'BG', label: 'Bunge' },
  { symbol: 'BIIB', label: 'Biogen' },
  { symbol: 'BIO', label: 'Bio-Rad' },
  { symbol: 'BK', label: 'BNY Mellon' },
  { symbol: 'BKNG', label: 'Booking Holdings' },
  { symbol: 'BKR', label: 'Baker Hughes' },
  { symbol: 'BLDR', label: 'Builders FirstSource' },
  { symbol: 'BLK', label: 'BlackRock' },
  { symbol: 'BMY', label: 'Bristol-Myers Squibb' },
  { symbol: 'BR', label: 'Broadridge' },
  { symbol: 'BRO', label: 'Brown & Brown' },
  { symbol: 'BSX', label: 'Boston Scientific' },
  { symbol: 'BWA', label: 'BorgWarner' },
  { symbol: 'BX', label: 'Blackstone' },
  // C
  { symbol: 'C', label: 'Citigroup' },
  { symbol: 'CAG', label: 'Conagra' },
  { symbol: 'CAH', label: 'Cardinal Health' },
  { symbol: 'CARR', label: 'Carrier Global' },
  { symbol: 'CAT', label: 'Caterpillar' },
  { symbol: 'CB', label: 'Chubb' },
  { symbol: 'CBOE', label: 'Cboe Global Markets' },
  { symbol: 'CBRE', label: 'CBRE Group' },
  { symbol: 'CCI', label: 'Crown Castle' },
  { symbol: 'CCL', label: 'Carnival' },
  { symbol: 'CDNS', label: 'Cadence Design' },
  { symbol: 'CDW', label: 'CDW Corp' },
  { symbol: 'CE', label: 'Celanese' },
  { symbol: 'CEG', label: 'Constellation Energy' },
  { symbol: 'CF', label: 'CF Industries' },
  { symbol: 'CFG', label: 'Citizens Financial' },
  { symbol: 'CHD', label: 'Church & Dwight' },
  { symbol: 'CHRW', label: 'C.H. Robinson' },
  { symbol: 'CHTR', label: 'Charter Communications' },
  { symbol: 'CI', label: 'Cigna' },
  { symbol: 'CINF', label: 'Cincinnati Financial' },
  { symbol: 'CL', label: 'Colgate-Palmolive' },
  { symbol: 'CLX', label: 'Clorox' },
  { symbol: 'CMCSA', label: 'Comcast' },
  { symbol: 'CME', label: 'CME Group' },
  { symbol: 'CMG', label: 'Chipotle' },
  { symbol: 'CMI', label: 'Cummins' },
  { symbol: 'CMS', label: 'CMS Energy' },
  { symbol: 'CNC', label: 'Centene' },
  { symbol: 'CNP', label: 'CenterPoint Energy' },
  { symbol: 'COF', label: 'Capital One' },
  { symbol: 'COIN', label: 'Coinbase' },
  { symbol: 'COO', label: 'Cooper Companies' },
  { symbol: 'COP', label: 'ConocoPhillips' },
  { symbol: 'COR', label: 'Cencora' },
  { symbol: 'COST', label: 'Costco' },
  { symbol: 'CPAY', label: 'Corpay' },
  { symbol: 'CPB', label: 'Campbell Soup' },
  { symbol: 'CPRT', label: 'Copart' },
  { symbol: 'CPT', label: 'Camden Property' },
  { symbol: 'CRL', label: 'Charles River Labs' },
  { symbol: 'CRM', label: 'Salesforce' },
  { symbol: 'CRWD', label: 'CrowdStrike' },
  { symbol: 'CSCO', label: 'Cisco' },
  { symbol: 'CSGP', label: 'CoStar Group' },
  { symbol: 'CSX', label: 'CSX' },
  { symbol: 'CTAS', label: 'Cintas' },
  { symbol: 'CTRA', label: 'Coterra Energy' },
  { symbol: 'CTSH', label: 'Cognizant' },
  { symbol: 'CTVA', label: 'Corteva' },
  { symbol: 'CVS', label: 'CVS Health' },
  { symbol: 'CVX', label: 'Chevron' },
  { symbol: 'CZR', label: 'Caesars Entertainment' },
  // D
  { symbol: 'D', label: 'Dominion Energy' },
  { symbol: 'DAL', label: 'Delta Air Lines' },
  { symbol: 'DAY', label: 'Dayforce' },
  { symbol: 'DD', label: 'DuPont' },
  { symbol: 'DE', label: 'Deere' },
  { symbol: 'DECK', label: 'Deckers Outdoor' },
  { symbol: 'DELL', label: 'Dell' },
  { symbol: 'DFS', label: 'Discover Financial' },
  { symbol: 'DG', label: 'Dollar General' },
  { symbol: 'DGX', label: 'Quest Diagnostics' },
  { symbol: 'DHI', label: 'D.R. Horton' },
  { symbol: 'DHR', label: 'Danaher' },
  { symbol: 'DIS', label: 'Disney' },
  { symbol: 'DLR', label: 'Digital Realty' },
  { symbol: 'DLTR', label: 'Dollar Tree' },
  { symbol: 'DOC', label: 'Healthpeak Properties' },
  { symbol: 'DOV', label: 'Dover' },
  { symbol: 'DOW', label: 'Dow' },
  { symbol: 'DPZ', label: "Domino's" },
  { symbol: 'DRI', label: 'Darden Restaurants' },
  { symbol: 'DTE', label: 'DTE Energy' },
  { symbol: 'DUK', label: 'Duke Energy' },
  { symbol: 'DVA', label: 'DaVita' },
  { symbol: 'DVN', label: 'Devon Energy' },
  { symbol: 'DXCM', label: 'DexCom' },
  // E
  { symbol: 'EA', label: 'Electronic Arts' },
  { symbol: 'EBAY', label: 'eBay' },
  { symbol: 'ECL', label: 'Ecolab' },
  { symbol: 'ED', label: 'Consolidated Edison' },
  { symbol: 'EFX', label: 'Equifax' },
  { symbol: 'EG', label: 'Everest Group' },
  { symbol: 'EIX', label: 'Edison International' },
  { symbol: 'EL', label: 'Estée Lauder' },
  { symbol: 'ELV', label: 'Elevance Health' },
  { symbol: 'EMN', label: 'Eastman Chemical' },
  { symbol: 'EMR', label: 'Emerson Electric' },
  { symbol: 'ENPH', label: 'Enphase Energy' },
  { symbol: 'EOG', label: 'EOG Resources' },
  { symbol: 'EPAM', label: 'EPAM Systems' },
  { symbol: 'EQIX', label: 'Equinix' },
  { symbol: 'EQR', label: 'Equity Residential' },
  { symbol: 'EQT', label: 'EQT' },
  { symbol: 'ES', label: 'Eversource Energy' },
  { symbol: 'ESS', label: 'Essex Property' },
  { symbol: 'ETN', label: 'Eaton' },
  { symbol: 'ETR', label: 'Entergy' },
  { symbol: 'EVRG', label: 'Evergy' },
  { symbol: 'EW', label: 'Edwards Lifesciences' },
  { symbol: 'EXC', label: 'Exelon' },
  { symbol: 'EXE', label: 'Expand Energy' },
  { symbol: 'EXPD', label: 'Expeditors' },
  { symbol: 'EXPE', label: 'Expedia' },
  { symbol: 'EXR', label: 'Extra Space Storage' },
  // F
  { symbol: 'F', label: 'Ford' },
  { symbol: 'FANG', label: 'Diamondback Energy' },
  { symbol: 'FAST', label: 'Fastenal' },
  { symbol: 'FCX', label: 'Freeport-McMoRan' },
  { symbol: 'FDS', label: 'FactSet' },
  { symbol: 'FDX', label: 'FedEx' },
  { symbol: 'FE', label: 'FirstEnergy' },
  { symbol: 'FFIV', label: 'F5' },
  { symbol: 'FI', label: 'Fiserv' },
  { symbol: 'FICO', label: 'Fair Isaac' },
  { symbol: 'FIS', label: 'FIS' },
  { symbol: 'FITB', label: 'Fifth Third Bancorp' },
  { symbol: 'FOX', label: 'Fox B' },
  { symbol: 'FOXA', label: 'Fox A' },
  { symbol: 'FRT', label: 'Federal Realty' },
  { symbol: 'FSLR', label: 'First Solar' },
  { symbol: 'FTNT', label: 'Fortinet' },
  { symbol: 'FTV', label: 'Fortive' },
  // G
  { symbol: 'GD', label: 'General Dynamics' },
  { symbol: 'GDDY', label: 'GoDaddy' },
  { symbol: 'GE', label: 'GE Aerospace' },
  { symbol: 'GEHC', label: 'GE HealthCare' },
  { symbol: 'GEN', label: 'Gen Digital' },
  { symbol: 'GEV', label: 'GE Vernova' },
  { symbol: 'GILD', label: 'Gilead Sciences' },
  { symbol: 'GIS', label: 'General Mills' },
  { symbol: 'GL', label: 'Globe Life' },
  { symbol: 'GLW', label: 'Corning' },
  { symbol: 'GM', label: 'General Motors' },
  { symbol: 'GOOG', label: 'Alphabet C' },
  { symbol: 'GOOGL', label: 'Alphabet A' },
  { symbol: 'GPC', label: 'Genuine Parts' },
  { symbol: 'GPN', label: 'Global Payments' },
  { symbol: 'GRMN', label: 'Garmin' },
  { symbol: 'GS', label: 'Goldman Sachs' },
  { symbol: 'GWW', label: 'W.W. Grainger' },
  // H
  { symbol: 'HAL', label: 'Halliburton' },
  { symbol: 'HAS', label: 'Hasbro' },
  { symbol: 'HBAN', label: 'Huntington Bancshares' },
  { symbol: 'HCA', label: 'HCA Healthcare' },
  { symbol: 'HD', label: 'Home Depot' },
  { symbol: 'HES', label: 'Hess' },
  { symbol: 'HIG', label: 'Hartford Financial' },
  { symbol: 'HII', label: 'Huntington Ingalls' },
  { symbol: 'HLT', label: 'Hilton' },
  { symbol: 'HOLX', label: 'Hologic' },
  { symbol: 'HON', label: 'Honeywell' },
  { symbol: 'HPE', label: 'HP Enterprise' },
  { symbol: 'HPQ', label: 'HP' },
  { symbol: 'HRL', label: 'Hormel Foods' },
  { symbol: 'HSIC', label: 'Henry Schein' },
  { symbol: 'HST', label: 'Host Hotels' },
  { symbol: 'HSY', label: 'Hershey' },
  { symbol: 'HUBB', label: 'Hubbell' },
  { symbol: 'HUM', label: 'Humana' },
  { symbol: 'HWM', label: 'Howmet Aerospace' },
  // I
  { symbol: 'IBM', label: 'IBM' },
  { symbol: 'ICE', label: 'Intercontinental Exchange' },
  { symbol: 'IDXX', label: 'Idexx Labs' },
  { symbol: 'IEX', label: 'IDEX' },
  { symbol: 'IFF', label: 'IFF' },
  { symbol: 'INCY', label: 'Incyte' },
  { symbol: 'INTC', label: 'Intel' },
  { symbol: 'INTU', label: 'Intuit' },
  { symbol: 'INVH', label: 'Invitation Homes' },
  { symbol: 'IP', label: 'International Paper' },
  { symbol: 'IPG', label: 'Interpublic Group' },
  { symbol: 'IQV', label: 'IQVIA' },
  { symbol: 'IR', label: 'Ingersoll Rand' },
  { symbol: 'IRM', label: 'Iron Mountain' },
  { symbol: 'ISRG', label: 'Intuitive Surgical' },
  { symbol: 'IT', label: 'Gartner' },
  { symbol: 'ITW', label: 'Illinois Tool Works' },
  { symbol: 'IVZ', label: 'Invesco' },
  // J
  { symbol: 'J', label: 'Jacobs Solutions' },
  { symbol: 'JBHT', label: 'J.B. Hunt' },
  { symbol: 'JBL', label: 'Jabil' },
  { symbol: 'JCI', label: 'Johnson Controls' },
  { symbol: 'JKHY', label: 'Jack Henry' },
  { symbol: 'JNJ', label: 'Johnson & Johnson' },
  { symbol: 'JNPR', label: 'Juniper Networks' },
  { symbol: 'JPM', label: 'JPMorgan' },
  // K
  { symbol: 'K', label: 'Kellanova' },
  { symbol: 'KDP', label: 'Keurig Dr Pepper' },
  { symbol: 'KEY', label: 'KeyCorp' },
  { symbol: 'KEYS', label: 'Keysight' },
  { symbol: 'KHC', label: 'Kraft Heinz' },
  { symbol: 'KIM', label: 'Kimco Realty' },
  { symbol: 'KKR', label: 'KKR' },
  { symbol: 'KLAC', label: 'KLA' },
  { symbol: 'KMB', label: 'Kimberly-Clark' },
  { symbol: 'KMI', label: 'Kinder Morgan' },
  { symbol: 'KMX', label: 'CarMax' },
  { symbol: 'KO', label: 'Coca-Cola' },
  { symbol: 'KR', label: 'Kroger' },
  { symbol: 'KVUE', label: 'Kenvue' },
  // L
  { symbol: 'L', label: 'Loews' },
  { symbol: 'LDOS', label: 'Leidos' },
  { symbol: 'LEN', label: 'Lennar' },
  { symbol: 'LH', label: 'Labcorp' },
  { symbol: 'LHX', label: 'L3Harris' },
  { symbol: 'LIN', label: 'Linde' },
  { symbol: 'LKQ', label: 'LKQ Corp' },
  { symbol: 'LLY', label: 'Eli Lilly' },
  { symbol: 'LMT', label: 'Lockheed Martin' },
  { symbol: 'LNT', label: 'Alliant Energy' },
  { symbol: 'LOW', label: "Lowe's" },
  { symbol: 'LRCX', label: 'Lam Research' },
  { symbol: 'LULU', label: 'Lululemon' },
  { symbol: 'LUV', label: 'Southwest Airlines' },
  { symbol: 'LVS', label: 'Las Vegas Sands' },
  { symbol: 'LW', label: 'Lamb Weston' },
  { symbol: 'LYB', label: 'LyondellBasell' },
  { symbol: 'LYV', label: 'Live Nation' },
  // M
  { symbol: 'MA', label: 'Mastercard' },
  { symbol: 'MAA', label: 'Mid-America Apartment' },
  { symbol: 'MAR', label: 'Marriott' },
  { symbol: 'MAS', label: 'Masco' },
  { symbol: 'MCD', label: "McDonald's" },
  { symbol: 'MCHP', label: 'Microchip Technology' },
  { symbol: 'MCK', label: 'McKesson' },
  { symbol: 'MCO', label: "Moody's" },
  { symbol: 'MDLZ', label: 'Mondelez' },
  { symbol: 'MDT', label: 'Medtronic' },
  { symbol: 'MET', label: 'MetLife' },
  { symbol: 'META', label: 'Meta' },
  { symbol: 'MGM', label: 'MGM Resorts' },
  { symbol: 'MHK', label: 'Mohawk Industries' },
  { symbol: 'MKC', label: 'McCormick' },
  { symbol: 'MKTX', label: 'MarketAxess' },
  { symbol: 'MLM', label: 'Martin Marietta' },
  { symbol: 'MMC', label: 'Marsh & McLennan' },
  { symbol: 'MMM', label: '3M' },
  { symbol: 'MNST', label: 'Monster Beverage' },
  { symbol: 'MO', label: 'Altria' },
  { symbol: 'MOH', label: 'Molina Healthcare' },
  { symbol: 'MOS', label: 'Mosaic' },
  { symbol: 'MPC', label: 'Marathon Petroleum' },
  { symbol: 'MPWR', label: 'Monolithic Power' },
  { symbol: 'MRK', label: 'Merck' },
  { symbol: 'MRNA', label: 'Moderna' },
  { symbol: 'MS', label: 'Morgan Stanley' },
  { symbol: 'MSCI', label: 'MSCI' },
  { symbol: 'MSFT', label: 'Microsoft' },
  { symbol: 'MSI', label: 'Motorola Solutions' },
  { symbol: 'MTB', label: 'M&T Bank' },
  { symbol: 'MTCH', label: 'Match Group' },
  { symbol: 'MTD', label: 'Mettler-Toledo' },
  { symbol: 'MU', label: 'Micron' },
  // N
  { symbol: 'NCLH', label: 'Norwegian Cruise Line' },
  { symbol: 'NDAQ', label: 'Nasdaq' },
  { symbol: 'NDSN', label: 'Nordson' },
  { symbol: 'NEE', label: 'NextEra Energy' },
  { symbol: 'NEM', label: 'Newmont' },
  { symbol: 'NFLX', label: 'Netflix' },
  { symbol: 'NI', label: 'NiSource' },
  { symbol: 'NKE', label: 'Nike' },
  { symbol: 'NOC', label: 'Northrop Grumman' },
  { symbol: 'NOW', label: 'ServiceNow' },
  { symbol: 'NRG', label: 'NRG Energy' },
  { symbol: 'NSC', label: 'Norfolk Southern' },
  { symbol: 'NTAP', label: 'NetApp' },
  { symbol: 'NTRS', label: 'Northern Trust' },
  { symbol: 'NUE', label: 'Nucor' },
  { symbol: 'NVDA', label: 'Nvidia' },
  { symbol: 'NVR', label: 'NVR' },
  { symbol: 'NWS', label: 'News Corp B' },
  { symbol: 'NWSA', label: 'News Corp A' },
  { symbol: 'NXPI', label: 'NXP Semiconductors' },
  // O
  { symbol: 'O', label: 'Realty Income' },
  { symbol: 'ODFL', label: 'Old Dominion Freight' },
  { symbol: 'OKE', label: 'ONEOK' },
  { symbol: 'OMC', label: 'Omnicom' },
  { symbol: 'ON', label: 'ON Semiconductor' },
  { symbol: 'ORCL', label: 'Oracle' },
  { symbol: 'ORLY', label: "O'Reilly Automotive" },
  { symbol: 'OTIS', label: 'Otis Worldwide' },
  { symbol: 'OXY', label: 'Occidental Petroleum' },
  // P
  { symbol: 'PANW', label: 'Palo Alto Networks' },
  { symbol: 'PARA', label: 'Paramount' },
  { symbol: 'PAYC', label: 'Paycom' },
  { symbol: 'PAYX', label: 'Paychex' },
  { symbol: 'PCAR', label: 'PACCAR' },
  { symbol: 'PCG', label: 'PG&E' },
  { symbol: 'PEG', label: 'Public Service Enterprise' },
  { symbol: 'PEP', label: 'PepsiCo' },
  { symbol: 'PFE', label: 'Pfizer' },
  { symbol: 'PFG', label: 'Principal Financial' },
  { symbol: 'PG', label: 'Procter & Gamble' },
  { symbol: 'PGR', label: 'Progressive' },
  { symbol: 'PH', label: 'Parker-Hannifin' },
  { symbol: 'PHM', label: 'PulteGroup' },
  { symbol: 'PKG', label: 'Packaging Corp' },
  { symbol: 'PLD', label: 'Prologis' },
  { symbol: 'PLTR', label: 'Palantir' },
  { symbol: 'PM', label: 'Philip Morris' },
  { symbol: 'PNC', label: 'PNC Financial' },
  { symbol: 'PNR', label: 'Pentair' },
  { symbol: 'PNW', label: 'Pinnacle West' },
  { symbol: 'PODD', label: 'Insulet' },
  { symbol: 'POOL', label: 'Pool Corp' },
  { symbol: 'PPG', label: 'PPG Industries' },
  { symbol: 'PPL', label: 'PPL Corp' },
  { symbol: 'PRU', label: 'Prudential' },
  { symbol: 'PSA', label: 'Public Storage' },
  { symbol: 'PSX', label: 'Phillips 66' },
  { symbol: 'PTC', label: 'PTC' },
  { symbol: 'PWR', label: 'Quanta Services' },
  { symbol: 'PYPL', label: 'PayPal' },
  // Q
  { symbol: 'QCOM', label: 'Qualcomm' },
  // R
  { symbol: 'RCL', label: 'Royal Caribbean' },
  { symbol: 'REG', label: 'Regency Centers' },
  { symbol: 'REGN', label: 'Regeneron' },
  { symbol: 'RF', label: 'Regions Financial' },
  { symbol: 'RJF', label: 'Raymond James' },
  { symbol: 'RL', label: 'Ralph Lauren' },
  { symbol: 'RMD', label: 'ResMed' },
  { symbol: 'ROK', label: 'Rockwell Automation' },
  { symbol: 'ROL', label: 'Rollins' },
  { symbol: 'ROP', label: 'Roper Technologies' },
  { symbol: 'ROST', label: 'Ross Stores' },
  { symbol: 'RSG', label: 'Republic Services' },
  { symbol: 'RTX', label: 'RTX' },
  { symbol: 'RVTY', label: 'Revvity' },
  // S
  { symbol: 'SBAC', label: 'SBA Communications' },
  { symbol: 'SBUX', label: 'Starbucks' },
  { symbol: 'SCHW', label: 'Charles Schwab' },
  { symbol: 'SHW', label: 'Sherwin-Williams' },
  { symbol: 'SJM', label: 'J.M. Smucker' },
  { symbol: 'SLB', label: 'SLB' },
  { symbol: 'SMCI', label: 'Super Micro Computer' },
  { symbol: 'SNA', label: 'Snap-on' },
  { symbol: 'SNPS', label: 'Synopsys' },
  { symbol: 'SO', label: 'Southern Co' },
  { symbol: 'SOLV', label: 'Solventum' },
  { symbol: 'SPG', label: 'Simon Property' },
  { symbol: 'SPGI', label: 'S&P Global' },
  { symbol: 'SRE', label: 'Sempra' },
  { symbol: 'STE', label: 'Steris' },
  { symbol: 'STLD', label: 'Steel Dynamics' },
  { symbol: 'STT', label: 'State Street' },
  { symbol: 'STX', label: 'Seagate' },
  { symbol: 'STZ', label: 'Constellation Brands' },
  { symbol: 'SW', label: 'Smurfit Westrock' },
  { symbol: 'SWK', label: 'Stanley Black & Decker' },
  { symbol: 'SWKS', label: 'Skyworks' },
  { symbol: 'SYF', label: 'Synchrony Financial' },
  { symbol: 'SYK', label: 'Stryker' },
  { symbol: 'SYY', label: 'Sysco' },
  // T
  { symbol: 'T', label: 'AT&T' },
  { symbol: 'TAP', label: 'Molson Coors' },
  { symbol: 'TDG', label: 'TransDigm' },
  { symbol: 'TDY', label: 'Teledyne' },
  { symbol: 'TECH', label: 'Bio-Techne' },
  { symbol: 'TEL', label: 'TE Connectivity' },
  { symbol: 'TER', label: 'Teradyne' },
  { symbol: 'TFC', label: 'Truist Financial' },
  { symbol: 'TFX', label: 'Teleflex' },
  { symbol: 'TGT', label: 'Target' },
  { symbol: 'TJX', label: 'TJX Companies' },
  { symbol: 'TKO', label: 'TKO Group' },
  { symbol: 'TMO', label: 'Thermo Fisher' },
  { symbol: 'TMUS', label: 'T-Mobile' },
  { symbol: 'TPL', label: 'Texas Pacific Land' },
  { symbol: 'TPR', label: 'Tapestry' },
  { symbol: 'TRGP', label: 'Targa Resources' },
  { symbol: 'TRMB', label: 'Trimble' },
  { symbol: 'TROW', label: 'T. Rowe Price' },
  { symbol: 'TRV', label: 'Travelers' },
  { symbol: 'TSCO', label: 'Tractor Supply' },
  { symbol: 'TSLA', label: 'Tesla' },
  { symbol: 'TSN', label: 'Tyson Foods' },
  { symbol: 'TT', label: 'Trane Technologies' },
  { symbol: 'TTWO', label: 'Take-Two' },
  { symbol: 'TXN', label: 'Texas Instruments' },
  { symbol: 'TXT', label: 'Textron' },
  { symbol: 'TYL', label: 'Tyler Technologies' },
  // U
  { symbol: 'UAL', label: 'United Airlines' },
  { symbol: 'UBER', label: 'Uber' },
  { symbol: 'UDR', label: 'UDR' },
  { symbol: 'UHS', label: 'Universal Health' },
  { symbol: 'ULTA', label: 'Ulta Beauty' },
  { symbol: 'UNH', label: 'UnitedHealth' },
  { symbol: 'UNP', label: 'Union Pacific' },
  { symbol: 'UPS', label: 'UPS' },
  { symbol: 'URI', label: 'United Rentals' },
  { symbol: 'USB', label: 'U.S. Bancorp' },
  // V
  { symbol: 'V', label: 'Visa' },
  { symbol: 'VICI', label: 'VICI Properties' },
  { symbol: 'VLO', label: 'Valero Energy' },
  { symbol: 'VLTO', label: 'Veralto' },
  { symbol: 'VMC', label: 'Vulcan Materials' },
  { symbol: 'VRSK', label: 'Verisk' },
  { symbol: 'VRSN', label: 'VeriSign' },
  { symbol: 'VRTX', label: 'Vertex Pharmaceuticals' },
  { symbol: 'VST', label: 'Vistra' },
  { symbol: 'VTR', label: 'Ventas' },
  { symbol: 'VTRS', label: 'Viatris' },
  { symbol: 'VZ', label: 'Verizon' },
  // W
  { symbol: 'WAB', label: 'Wabtec' },
  { symbol: 'WAT', label: 'Waters' },
  { symbol: 'WBA', label: 'Walgreens' },
  { symbol: 'WBD', label: 'Warner Bros. Discovery' },
  { symbol: 'WDC', label: 'Western Digital' },
  { symbol: 'WEC', label: 'WEC Energy' },
  { symbol: 'WELL', label: 'Welltower' },
  { symbol: 'WFC', label: 'Wells Fargo' },
  { symbol: 'WM', label: 'Waste Management' },
  { symbol: 'WMB', label: 'Williams Companies' },
  { symbol: 'WMT', label: 'Walmart' },
  { symbol: 'WRB', label: 'W.R. Berkley' },
  { symbol: 'WSM', label: 'Williams-Sonoma' },
  { symbol: 'WST', label: 'West Pharmaceutical' },
  { symbol: 'WTW', label: 'Willis Towers Watson' },
  { symbol: 'WY', label: 'Weyerhaeuser' },
  { symbol: 'WYNN', label: 'Wynn Resorts' },
  // X-Z
  { symbol: 'XEL', label: 'Xcel Energy' },
  { symbol: 'XOM', label: 'ExxonMobil' },
  { symbol: 'XYL', label: 'Xylem' },
  { symbol: 'YUM', label: 'Yum! Brands' },
  { symbol: 'ZBH', label: 'Zimmer Biomet' },
  { symbol: 'ZBRA', label: 'Zebra Technologies' },
  { symbol: 'ZTS', label: 'Zoetis' },

  // ── SOXX additions not in S&P 500 ──
  { symbol: 'TSM',  label: 'TSMC (ADR)' },
  { symbol: 'ASML', label: 'ASML (ADR)' },
  { symbol: 'ARM',  label: 'Arm Holdings' },
  { symbol: 'MRVL', label: 'Marvell' },

  // ── ETFs that aren't S&P 500 constituents but every options trader watches ──
  { symbol: 'SPY', label: 'S&P 500' },
  { symbol: 'QQQ', label: 'Nasdaq-100' },
  { symbol: 'IWM', label: 'Russell 2000' },
  { symbol: 'DIA', label: 'Dow Jones' },
  { symbol: 'GLD', label: 'Gold' },
  { symbol: 'SLV', label: 'Silver' },
  { symbol: 'TLT', label: '20y Treasury' },
  { symbol: 'USO', label: 'Crude Oil' },

  // ── Additional liquid options names + DRAM/memory ──
  { symbol: 'NVO',  label: 'Novo Nordisk' },
  { symbol: 'BABA', label: 'Alibaba' },
  { symbol: 'GME',  label: 'GameStop' },
]

// Set of hot-list symbols for quick `isHot` lookups in components.
export const HOT_SYMBOLS = new Set(HOT_TICKERS.map((t) => t.symbol))

// Deduplicated universe of all selectable tickers, sorted: hot first
// (in the original hot order so SPY/QQQ stay at the top), then the
// rest alphabetically.
export const TICKER_UNIVERSE = (() => {
  const seen = new Set()
  const out = []
  for (const t of HOT_TICKERS) {
    if (!seen.has(t.symbol)) {
      seen.add(t.symbol)
      out.push({ ...t, isHot: true })
    }
  }
  const rest = []
  for (const t of SP500_TICKERS) {
    if (!seen.has(t.symbol)) {
      seen.add(t.symbol)
      rest.push({ ...t, isHot: false })
    }
  }
  rest.sort((a, b) => a.symbol.localeCompare(b.symbol))
  return out.concat(rest)
})()
