"""Generate the edge-function copy of the LDP thresholds it needs.

The ``ldp-onboarding`` edge function computes the risk tier (so the
form can show it immediately) and renders the UI copy, which quotes the
satellite caps. Deno can't import the Python config, so this script
writes ``supabase/functions/_shared/ldpConfig.generated.ts`` from
:class:`ldp.config.LDPConfig` defaults. tests/test_edge_config.py fails
if the generated file is stale.

    python -m ldp.tools.export_edge_config
"""

from __future__ import annotations

import json
from pathlib import Path

from ldp.config import LDPConfig

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "supabase" / "functions" / "_shared" / "ldpConfig.generated.ts"


def render(cfg: LDPConfig | None = None) -> str:
    cfg = cfg or LDPConfig()
    data = {
        "risk": {
            "minAccountAggressive": cfg.risk.min_account_aggressive,
            "minHorizonYears": cfg.risk.min_horizon_years,
        },
        "satellite": {
            "maxPerName": cfg.satellite.max_per_name,
            "maxTotal": cfg.satellite.max_total,
        },
    }
    body = json.dumps(data, indent=2)
    return (
        "// GENERATED by `python -m ldp.tools.export_edge_config` from ldp/config.py.\n"
        "// Do not edit by hand — change the Python config and regenerate.\n"
        f"export const LDP_CONFIG = {body} as const\n"
    )


def main() -> int:
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
