// GENERATED by `python -m ldp.tools.export_edge_config` from ldp/config.py.
// Do not edit by hand — change the Python config and regenerate.
export const LDP_CONFIG = {
  "risk": {
    "minAccountAggressive": 25000.0,
    "minHorizonYears": 2.0
  },
  "satellite": {
    "maxPerName": 0.05,
    "maxTotal": 0.15
  }
} as const
