// GENERATED by scripts/sync-orderflow.mjs from src/utils/orderflow/ — do not edit here.
// Trading-session labels in US Eastern time.
//   overnight   20:00–04:00 (next day)  — ATS-only liquidity
//   premarket   04:00–09:30
//   regular     09:30–16:00
//   afterhours  16:00–20:00
// Weekends (Sat, and Sun before 20:00) are 'closed'. Exchange holidays
// are not modelled; a holiday simply has no prints.

const fmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/New_York', hourCycle: 'h23',
  year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', weekday: 'short',
})
const cache = new Map()

// { date: 'YYYY-MM-DD', minute: minutes since ET midnight, dow: 0–6 }
export function etParts(ms) {
  const key = Math.floor(ms / 60_000)
  const hit = cache.get(key)
  if (hit) return hit
  const p = {}
  for (const { type, value } of fmt.formatToParts(new Date(key * 60_000))) p[type] = value
  const dow = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(p.weekday)
  const out = { date: `${p.year}-${p.month}-${p.day}`, minute: Number(p.hour) * 60 + Number(p.minute), dow }
  if (cache.size > 5000) cache.clear()
  cache.set(key, out)
  return out
}

export function sessionOf(ms) {
  const { minute, dow } = etParts(ms)
  // Overnight runs Sun 20:00 → Mon 04:00 … Thu 20:00 → Fri 04:00.
  if (minute < 4 * 60) return dow >= 1 && dow <= 5 ? 'overnight' : 'closed'
  if (dow === 0) return minute >= 20 * 60 ? 'overnight' : 'closed'
  if (dow === 6) return 'closed'
  if (minute < 9 * 60 + 30) return 'premarket'
  if (minute < 16 * 60) return 'regular'
  if (minute < 20 * 60) return 'afterhours'
  return dow === 5 ? 'closed' : 'overnight'
}

// Session key — trades in the same session share a CVD. An overnight
// session that started the previous evening keys on that evening's date.
export function sessionKey(ms) {
  const s = sessionOf(ms)
  const { date, minute } = etParts(ms)
  if (s === 'overnight' && minute < 4 * 60) {
    const prev = etParts(ms - 6 * 3_600_000).date
    return `${prev}:overnight`
  }
  return `${date}:${s}`
}

export const SESSION_LABEL = Object.freeze({
  premarket: 'Premarket', regular: 'Regular', afterhours: 'After hours', overnight: 'Overnight', closed: 'Closed',
})
