// GENERATED by scripts/sync-orderflow.mjs from src/utils/orderflow/ — do not edit here.
// SYNTHETIC DEMO data for NIGHTFLOW. Scripted, seeded scenarios that
// exercise each detector and the dashboard. This is generated data, not
// market data — every consumer must label it as such.

import { rng } from './stats.js'

export const SCENARIOS = Object.freeze({
  accumulation: { label: 'Bullish accumulation', blurb: 'Steady net buying lifts price with higher lows; bids stay healthy.' },
  sell_absorption: { label: 'Sell-side absorption', blurb: 'Heavy buying into a refilling seller at one level; price stalls, fails a break, then slips.' },
  distribution: { label: 'Distribution after a run', blurb: 'A +40% run, repeated rejection at the high, fading delta, thinning bids, wider spread.' },
  liquidity_withdrawal: { label: 'Liquidity withdrawal → selling', blurb: 'Bids are pulled without trades, the spread gaps, then aggressive selling accelerates.' },
  quiet: { label: 'Thin tape (insufficient data)', blurb: 'Too few prints to say anything — the engine should refuse to score.' },
})

// 10:00 ET on a weekday, so the regular-session coverage applies.
const DEFAULT_START = Date.UTC(2026, 9, 7, 14, 0, 0)

export function generateScenario(name = 'sell_absorption', { seed = 7, start = DEFAULT_START, minutes = 60, warmup = 35 } = {}) {
  const R = rng(seed + name.length * 101)
  const gauss = () => { let u = 0, v = 0; while (!u) u = R(); while (!v) v = R(); return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v) }
  const tick = 0.01
  const events = []
  let mid = name === 'distribution' ? 2.0 : 4.0
  let spreadTicks = 2
  let bidSize = 3000, askSize = 3000
  let bidDepth = 1, idSeq = 0
  const ceiling = 4.2

  const phase = (sec) => (sec < warmup * 60 ? 'warm' : 'act')
  for (let sec = 0; sec < minutes * 60; sec++) {
    const t0 = start + sec * 1000
    const ph = phase(sec)
    const into = ph === 'act' ? (sec - warmup * 60) / ((minutes - warmup) * 60) : 0
    let rate = 1.2, pBuy = 0.5, drift = 0, impact = 0.0000025, vol = 0.0006
    spreadTicks = 2; bidDepth = 1

    if (name === 'quiet') { rate = 0.02 }
    if (name === 'accumulation' && ph === 'act') { pBuy = 0.62; drift = 0.00002; rate = 1.6; impact = 0.0000008 }
    if (name === 'sell_absorption') {
      if (ph === 'warm') { drift = 0.00001 }
      else { rate = 2.6; pBuy = into < 0.85 ? 0.78 : 0.3; impact = into < 0.85 ? 0.0000003 : 0.0000015 }
    }
    if (name === 'distribution') {
      if (ph === 'warm') { drift = 0.00009; pBuy = 0.58; rate = 2; impact = 0.0000008 }
      else {
        rate = 2.2; impact = 0.0000008
        pBuy = 0.5 - 0.15 * into
        bidDepth = 1 - 0.65 * into
        spreadTicks = 2 + Math.round(4 * into)
        drift = into < 0.5 ? 0.00006 * Math.sin(into * 40) : -0.00004
      }
    }
    if (name === 'liquidity_withdrawal' && ph === 'act') {
      if (into < 0.3) { /* normal */ }
      else if (into < 0.36) { bidDepth = 0.08; spreadTicks = 7; rate = 0.4 }
      else { bidDepth = 0.25; spreadTicks = 6; rate = 4.5; pBuy = 0.18; impact = 0.0000004 }
    }

    // price path
    mid = mid * (1 + drift + vol * gauss() * 0.3)
    const n = Math.floor(rate) + (R() < rate - Math.floor(rate) ? 1 : 0)
    const spread = spreadTicks * tick
    let netShares = 0
    const trades = []
    for (let k = 0; k < n; k++) {
      const buy = R() < pBuy
      const size = Math.max(100, Math.round(Math.exp(5.6 + 0.8 * gauss()) / 100) * 100)
      trades.push({ buy, size, ms: Math.floor(R() * 900) })
      netShares += buy ? size : -size
    }
    mid = mid * (1 + impact * netShares)
    if (name === 'sell_absorption' && ph === 'act' && into < 0.85) {
      // The seller at the ceiling: ask pinned there, refilled after every hit.
      const failedBreak = into > 0.7 && into < 0.74
      mid = Math.min(mid, ceiling - spread / 2 + (failedBreak ? 0.03 : 0))
      if (mid < ceiling - spread / 2 - 0.02) mid += 0.004
    }
    mid = Math.max(mid, 0.5)

    const bid = Math.round((mid - spread / 2) / tick) * tick
    const ask = Math.round((bid + spread) / tick) * tick
    bidSize = Math.max(100, Math.round((2000 + 2500 * R()) * bidDepth / 100) * 100)
    askSize = name === 'sell_absorption' && ph === 'act' && into < 0.85 ? 500 : Math.max(100, Math.round((2000 + 2500 * R()) / 100) * 100)

    events.push({ kind: 'quote', t: t0, bid: +bid.toFixed(2), ask: +ask.toFixed(2), bidSize, askSize })
    // Level 2: 10 levels a side; bid depth scales with the scenario.
    const lvl = (side) => Array.from({ length: 10 }, (_, i) => [
      +(side === 'bid' ? bid - i * tick : ask + i * tick).toFixed(2),
      Math.max(100, Math.round(((side === 'bid' ? bidSize : askSize) * (1 + 0.3 * i) * (side === 'bid' ? 1 : 1)) / 100) * 100),
    ])
    if (sec % 2 === 0) events.push({ kind: 'book', t: t0 + 1, bids: lvl('bid'), asks: lvl('ask') })

    for (const tr of trades.sort((a, b) => a.ms - b.ms)) {
      const px = tr.buy ? ask : bid
      events.push({ kind: 'trade', t: t0 + 5 + tr.ms, price: +px.toFixed(2), size: tr.size, id: `syn${++idSeq}`, bid: +bid.toFixed(2), ask: +ask.toFixed(2), conds: '' })
    }
  }
  events.sort((a, b) => a.t - b.t)
  return { events, symbol: 'DEMO', scenario: name, label: SCENARIOS[name]?.label ?? name, start, end: start + minutes * 60_000, warmupEnd: start + warmup * 60_000, synthetic: true }
}
